name: Android CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Assemble debug
      run: ./gradlew assembleDebug
  
  unit_test:
    needs: [build]
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run unit test
      run: ./gradlew :library:testDebugUnitTest
  
  android_test:
    needs: [build]
    runs-on: macOS-latest
    strategy:
      matrix:
        # Waiting mockk fix of verify(timeout = ...) with API < 24
        api-level: [24, 28]
        target: [default]

    steps:
    - uses: actions/checkout@v1
    - name: Run instrumented test
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        headless: true
        disable-animations: false
        script: ./gradlew :library:connectedCheck
